### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by paazmaya** [LambdaTest/node-tunnel#1]
Would it be possible to git tag releases, so that comparing changes between release would be easier?
Currently there are no tags at all, but npm has:

```sh
$ npm info @lambdatest/node-tunnel versions
[ '1.0.0', '1.0.1', '1.0.2', '1.0.3' ]
```

**Comment by 4DvAnCeBoY** [comment]
@paazmaya thanks for the suggestion, we have added tags for each release.

**Comment by manish-lt** [comment]
This will really helps alot
