### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by ianwalter** [LambdaTest/node-tunnel#10]
I'm trying to use this but it doesn't seem to be working even though the output says "Tunnel successfully initiated. You can start testing now" and I can't find documentation on LambdaTest for using this specifically.

**Comment by ianwalter** [comment]
I think the issue is that I need to pass the tunnel name to the webdriver instance, but I can't find any information on how to do that.

**Comment by ianwalter** [comment]
So I figured out that I need to add `tunnel: tunnelName` to the capabilities but was not sure since I thought maybe I would get the `Illegal key values seen in w3c capabilities` error I was getting before. I think it would be helpful to have some documentation specifically for this.

**Comment by akshatlambdatest** [comment]
Hi @ianwalter, just wanted to check is this resolved.
