### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by XhmikosR** [LambdaTest/node-tunnel#35]
1. update dependencies
2. fix CI
3. fix lint
4. establish supported Node.js versions
5. *bonus* see if you can reduce your dependencies/devDependencies and sort out any open PRs :)

**Comment by Shivanshu-lambdatest** [comment]
Thanks, @XhmikosR for your suggestions. We have published a new version 4.0.0 with updated dependencies and the supported node version. We will be incorporating further suggestions in subsequent updates.
