### ISSUE TITLE
TypeScript definitions appears to be incorrect

### ISSUE THREAD

**Issue by NicHaley** [LambdaTest/node-tunnel#6]
TS definitions do not match method usage in docs. For example, the docs describe both callback and promise compatibility for the [stop method](https://github.com/LambdaTest/node-tunnel#tunnelinstancestopcallback). Based on the docs, the TS definitions should be `stop(callback: (err?: Error, status: string) => void): Promise<void>;`. Instead, it's `stop(callback: () => void): void;`.

**Comment by kanhaiya15** [comment]
Hi @NicHaley , Sorry for the late response and thanks for this change suggestion. I will do this change on upcomming release.
Thanks again , Stay safe

Reagrds,
Kanhaiya

**Comment by Shivanshu-lambdatest** [comment]
@NicHaley This change was done.

**Comment by dubesar** [comment]
Closing this ticket due to inactivity.
